# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextReplacement_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 204)
        self.PB_Replace = QtWidgets.QPushButton(Form)
        self.PB_Replace.setGeometry(QtCore.QRect(580, 150, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Replace.setFont(font)
        self.PB_Replace.setObjectName("PB_Replace")
        self.LE_FilePath = QtWidgets.QLineEdit(Form)
        self.LE_FilePath.setGeometry(QtCore.QRect(130, 40, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LE_FilePath.setFont(font)
        self.LE_FilePath.setObjectName("LE_FilePath")
        self.LE_OriginalText = QtWidgets.QLineEdit(Form)
        self.LE_OriginalText.setGeometry(QtCore.QRect(140, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LE_OriginalText.setFont(font)
        self.LE_OriginalText.setObjectName("LE_OriginalText")
        self.LE_ReplacementText = QtWidgets.QLineEdit(Form)
        self.LE_ReplacementText.setGeometry(QtCore.QRect(540, 100, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LE_ReplacementText.setFont(font)
        self.LE_ReplacementText.setObjectName("LE_ReplacementText")
        self.L_FilePath = QtWidgets.QLabel(Form)
        self.L_FilePath.setGeometry(QtCore.QRect(20, 50, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.L_FilePath.setFont(font)
        self.L_FilePath.setObjectName("L_FilePath")
        self.L_OriginalText = QtWidgets.QLabel(Form)
        self.L_OriginalText.setGeometry(QtCore.QRect(20, 110, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.L_OriginalText.setFont(font)
        self.L_OriginalText.setObjectName("L_OriginalText")
        self.L_ReplacementText = QtWidgets.QLabel(Form)
        self.L_ReplacementText.setGeometry(QtCore.QRect(363, 110, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.L_ReplacementText.setFont(font)
        self.L_ReplacementText.setObjectName("L_ReplacementText")
        self.L_Status = QtWidgets.QLabel(Form)
        self.L_Status.setGeometry(QtCore.QRect(20, 170, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.L_Status.setFont(font)
        self.L_Status.setObjectName("L_Status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PB_Replace.setText(_translate("Form", "Replace"))
        self.PB_Replace.setShortcut(_translate("Form", "Return"))
        self.L_FilePath.setText(_translate("Form", "File Path"))
        self.L_OriginalText.setText(_translate("Form", "Original Text"))
        self.L_ReplacementText.setText(_translate("Form", "Replacement Text"))
        self.L_Status.setText(_translate("Form", "Status:"))
